# Generated by Django 3.1.3 on 2020-12-09 12:26

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to=portfolio.models.random_file_name)),
                ('companyName', models.CharField(default='', max_length=200)),
                ('employees', models.CharField(blank=True, default='', max_length=200)),
                ('exchange', models.CharField(default='', max_length=200)),
                ('industry', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('ceo', models.CharField(blank=True, default='', max_length=200)),
                ('securityName', models.CharField(blank=True, default='', max_length=200)),
                ('issueType', models.CharField(blank=True, default='', max_length=200)),
                ('sector', models.CharField(blank=True, default='', max_length=200)),
                ('primarySicCode', models.CharField(blank=True, default='', max_length=200)),
                ('tags', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('address2', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('zip', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('price', models.CharField(default='', max_length=200)),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=1)),
                ('price', models.CharField(default='', max_length=200)),
                ('open', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.stock')),
            ],
        ),
    ]
